apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    type: redis
spec:
  selector:
    matchLabels:
      type: redis
  replicas: 2
  template:
    metadata:
      name: redis
      labels:
        type: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
    
    