apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    type: result-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    type: result-app
  
