apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    type: result-app-deploy
spec:
  selector:
    matchLabels:
      type: result-app
  replicas: 3
  template:
    metadata:
      name: result-app
      labels:
        type: result-app
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
              name: result-app

              
    
    
  

