apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    type: voting-app-deploy
spec:
  selector:
    matchLabels:
      type: voting-app
  replicas: 3
  template:
    metadata:
      name: voting-app
      labels:
        type: voting-app
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
              name: voting-app

              
    
    
  

